<a href="https://colab.research.google.com/github/jinxiqinghuan/learn_pytorch/blob/main/%E9%BE%99%E6%9B%B2%E8%89%AF%E8%80%81%E5%B8%88%E8%AF%BE%E7%A8%8B%E7%AC%94%E8%AE%B0/04_Pytorch%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 导库

In [3]:
import torch
import numpy as np

## pytorch 基础教程

### 1.张量数据类型

In [ ]:
a = torch.randn(2, 3)

In [ ]:
a.type 

<function Tensor.type>

In [ ]:
type(a)

torch.Tensor

#### instance判断数据类型

In [ ]:
isinstance(a, torch.FloatTensor)

True

In [ ]:
isinstance(a, torch.cuda.FloatTensor)

False

In [ ]:
a = a.cuda() #使用GPU

In [ ]:
isinstance(a, torch.cuda.FloatTensor)

True

In [ ]:
torch.tensor(1.)

tensor(1.)

In [ ]:
torch.tensor(1.3)

tensor(1.3000)

In [ ]:
a = torch.tensor(2.2)

#### 标量是0维的

In [ ]:
a.shape

torch.Size([])

In [ ]:
len(a.shape) # 标量是0维的

0

In [ ]:
a = torch.tensor([1.])
a

tensor([1.])

In [ ]:
len(a)

1

In [ ]:
a.size

<function Tensor.size>

In [ ]:
torch.tensor([1,1])

tensor([1, 1])

In [ ]:
a = torch.tensor([1.1, 2.2])
a

tensor([1.1000, 2.2000])

In [ ]:
torch.FloatTensor(1)

tensor([-1.2204])

#### 指定类型和维度初始化

In [ ]:
torch.FloatTensor(2, 3) # 随机初始化指定维度的tensor

tensor([[[-1.2206,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 0.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]])

In [ ]:
data = np.ones(2)
data

array([1., 1.])

In [ ]:
data = torch.from_numpy(data)
data

tensor([1., 1.], dtype=torch.float64)

#### 一维的tensor可以用在哪里？
1. bias偏置
2. [28, 28]->[784] batch=1的手写数据集


In [ ]:
print(data)

tensor([1., 1.], dtype=torch.float64)


In [ ]:
a = torch.ones(2)

In [ ]:
a, a.shape, a.size

(tensor([1., 1.]), torch.Size([2]), <function Tensor.size>)

In [ ]:
a = torch.randn(2, 3) # 随机正态分布

In [ ]:
a

tensor([[-0.7167, -0.3013, -0.9241],
        [ 0.5277,  2.5219, -1.2190]])

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
a.size(0) # 返回shape的第一个元素

2

In [ ]:
a.size(1) # 返回shape的第二个元素

3

#### 维度为2的使用场景:
[784] -> [4, 784]

In [ ]:
a = torch.rand(1, 2, 3)
a

tensor([[[0.7132, 0.6101, 0.2299],
         [0.7959, 0.6889, 0.6648]]])

In [ ]:
a.shape

torch.Size([1, 2, 3])

In [ ]:
a[0]

tensor([[0.7132, 0.6101, 0.2299],
        [0.7959, 0.6889, 0.6648]])

In [ ]:
list(a.shape) # 使用python的list方法，把返回的torch.Size直接转化成list类型

[1, 2, 3]

#### 使用torch.rand()进行初始化

In [ ]:
a = torch.rand(2, 3, 28, 28) # [b, c, h , w] b.第几张照片， c.通道数，  h,w.长*宽
a.shape

torch.Size([2, 3, 28, 28])

#### numel返回占用内存大小

In [ ]:
a.numel() # 2 * 3 * 28 * 28

4704

In [ ]:
2 * 3 * 28 * 28

4704

In [ ]:
a.dim()

4

### 2.创建Tensor

In [ ]:
a = np.array([2, 3.3])
a

array([2. , 3.3])

In [ ]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [ ]:
a = np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

#### torch.tensor()和torch.FloatTensor()
一般情况下，大写的Tensor接收的是数据的维度，而小写的接收的是数据

In [ ]:
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [ ]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000])

In [ ]:
torch.tensor([[2., 3.2], [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

#### 生成未初始化的数据
* torch.empty()
* torch.FloatTensor(d1, d2, d3)
* torch.IntTensor()

未初始化的tensor一定要跟写入数据的后续步骤, 只是暂时作为一个容器

In [ ]:
torch.empty(1)

tensor([-1.2203])

In [ ]:
torch.Tensor(2, 3) # 生成的数据非常不规则

tensor([[-1.2203e+00,  0.0000e+00,  1.5975e-43],
        [ 1.3873e-43,  1.4574e-43,  6.4460e-44]])

In [ ]:
torch.IntTensor(2, 3) 

tensor([[-1080282112,           0,          24],
        [          0,          -1,          46]], dtype=torch.int32)

In [ ]:
torch.FloatTensor(2, 2)

tensor([[-1.2203e+00,  0.0000e+00],
        [ 1.5975e-43,  1.3873e-43]])

#### 设置默认类型

In [ ]:
torch.tensor([1.2, 3]).type() # pytorch默认类型,更长使用Double类型

'torch.FloatTensor'

In [ ]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [ ]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

#### torch常用的随机初始化

In [ ]:
torch.rand(3, 3)

tensor([[0.7864, 0.1525, 0.1233],
        [0.0594, 0.9376, 0.4399],
        [0.3681, 0.5145, 0.8572]])

In [ ]:
a = torch.rand(3, 2)
a

tensor([[0.9234, 0.9789],
        [0.7305, 0.5540],
        [0.9511, 0.6229]])

#### 编程tips
在最近研究的GAN项目中，这里在成对图像的生成任务中，可以使用：生成图像 = torch.rand_like(原始图像) 生成噪声来进行输入

In [ ]:
torch.rand_like(a) 

tensor([[0.8654, 0.5623],
        [0.4267, 0.6323],
        [0.4710, 0.6784]])

In [ ]:
torch.randint(1, 10, [3, 3]) # 参数：最小值， 最大值， shape

tensor([[5, 6, 6],
        [1, 7, 1],
        [4, 2, 5]])

In [ ]:
torch.randn(3, 3)

tensor([[ 0.2031,  0.6228, -0.5930],
        [-1.6114, -1.2220, -1.2801],
        [ 0.7028,  0.9088, -0.3470]])

In [ ]:
# torch.normal(mean=torch.full([10],0), std=torch.arange(1, 0, -0.1))

In [ ]:
torch.full([2,3], 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [ ]:
torch.full([], 7)

tensor(7)

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.range(0, 10) # 不建议使用

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### torch.linspace()

In [ ]:
torch.linspace(0, 10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [ ]:
torch.linspace(0, 10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.linspace(0, 10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

#### 0,1,单位矩阵

In [ ]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### random.shuffle

In [ ]:
torch.randperm(10)

tensor([8, 2, 7, 0, 4, 5, 1, 9, 3, 6])

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 2)

In [ ]:
idx = torch.randperm(2)
idx

tensor([0, 1])

In [ ]:
idx

tensor([0, 1])

In [ ]:
a[idx]

tensor([[0.0734, 0.4379, 0.2059],
        [0.4562, 0.1850, 0.1916]])

In [ ]:
b[idx]

tensor([[0.1709, 0.7325],
        [0.0880, 0.3170]])

In [ ]:
a, b

(tensor([[0.0734, 0.4379, 0.2059],
         [0.4562, 0.1850, 0.1916]]), tensor([[0.1709, 0.7325],
         [0.0880, 0.3170]]))

### 3.索引与切片

#### 索引规则： start : end : step

In [ ]:
a = torch.rand(4, 3, 28, 28)
a[0].shape

torch.Size([3, 28, 28])

In [ ]:
a[0, 0].shape

torch.Size([28, 28])

In [ ]:
a[0, 0, 2, 4]

tensor(0.8190)

In [ ]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [ ]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 28, 28])

In [ ]:
a[:2, :-1, :, :].shape

torch.Size([2, 2, 28, 28])

In [ ]:
a[:, :, 0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [ ]:
a[:, :, ::2, ::2].shape

torch.Size([4, 3, 14, 14])

In [ ]:
a.shape

torch.Size([4, 3, 28, 28])

#### index_select()
 参数：选取的维度， 做出的改变（必须是torch.tensor）

In [ ]:
a.index_select(0, torch.tensor([0, 2])).shape

torch.Size([2, 3, 28, 28])

In [ ]:
a.index_select(0, torch.tensor([1 ,2])).shape

torch.Size([2, 3, 28, 28])

In [ ]:
a.index_select(2, torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [ ]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

#### 使用...来简化索引

In [ ]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [ ]:
a[0, ...].shape

torch.Size([3, 28, 28])

In [ ]:
a[:, 1, ...].shape

torch.Size([4, 28, 28])

In [ ]:
a[..., :2].shape

torch.Size([4, 3, 28, 2])

In [ ]:
x = torch.randn(3, 4)
x

tensor([[ 1.1545,  0.5730,  0.0829, -1.1386],
        [ 0.2590,  0.0364, -0.5729,  0.2742],
        [-1.0594,  0.8124,  0.7833,  0.0774]])

In [ ]:
mask = x.ge(0.5)

In [ ]:
mask

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False,  True,  True, False]])

In [ ]:
torch.masked_select(x, mask)

tensor([1.1545, 0.5730, 0.8124, 0.7833])

In [ ]:
src = torch.tensor([[4, 3, 5], [6, 7, 8]])

In [ ]:
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [ ]:
torch.take(src, torch.tensor([0, 2, 5])) # 打平（2*3->6）再取编码

tensor([4, 5, 8])

### 4.维度变换

* view/reshape
* squeeze/unsqueeze
* transpose/ t / permute
* expand/repeat

In [4]:
a = torch.rand(4, 1, 28, 28)
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
a.view(4, 28*28)

tensor([[0.5584, 0.2880, 0.5455,  ..., 0.9936, 0.8437, 0.8656],
        [0.4919, 0.6198, 0.8299,  ..., 0.8222, 0.3050, 0.7652],
        [0.2231, 0.5982, 0.1019,  ..., 0.1383, 0.3280, 0.9450],
        [0.7397, 0.1114, 0.1651,  ..., 0.7343, 0.8315, 0.7451]])

In [6]:
a.view(4, 28*28).shape

torch.Size([4, 784])

In [7]:
a.view(4*28, 28).shape

torch.Size([112, 28])

In [8]:
a.view(4, 28, 28).shape

torch.Size([4, 28, 28])

In [11]:
b = a.view(4, 784)
b.shape

torch.Size([4, 784])

In [15]:
b.view(4, 28, 28, 1).shape # 数据污染

torch.Size([4, 28, 28, 1])

In [ ]:
test