<a href="https://colab.research.google.com/github/jinxiqinghuan/learn_pytorch/blob/main/%E9%BE%99%E6%9B%B2%E8%89%AF%E8%80%81%E5%B8%88%E8%AF%BE%E7%A8%8B%E7%AC%94%E8%AE%B0/07_%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E4%B8%8E%E5%85%A8%E8%BF%9E%E6%8E%A5%E5%B1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 神经网络与全连接层

In [12]:
import torch
from torch.nn import functional as F
from matplotlib import pyplot as plt
import numpy as np

## 交叉熵

In [2]:
a = torch.full([4], 1/4)
a

tensor([0.2500, 0.2500, 0.2500, 0.2500])

In [3]:
a*torch.log2(a)

tensor([-0.5000, -0.5000, -0.5000, -0.5000])

In [5]:
-(a*torch.log2(a)).sum()

tensor(2.)

In [6]:
a = torch.tensor([0.1, 0.1, 0.1, 0.7])
a

tensor([0.1000, 0.1000, 0.1000, 0.7000])

In [7]:
-(a*torch.log2(a)).sum()

tensor(1.3568)

In [8]:
a = torch.tensor([0.001, 0.001, 0.001, 0.999])
-(a*torch.log2(a)).sum()

tensor(0.0313)

cross entropy

In [10]:
x = torch.randn(1, 784)
w = torch.randn(10, 784)

In [11]:
logits = x@w.t()

In [19]:
logits

tensor([[-26.5431,  -4.7924,  -6.0051,   0.9188,  10.6731,   1.8368,  51.4542,
          25.9747, -66.1441,  52.7316]])

In [14]:
pred = F.softmax(logits, dim=1)

In [20]:
pred

tensor([[2.9152e-35, 8.1444e-26, 2.4221e-26, 2.4616e-23, 4.2409e-19, 6.1645e-23,
         2.1799e-01, 1.8745e-12, 0.0000e+00, 7.8201e-01]])

In [24]:
min(pred[0]), max(pred[0])

(tensor(0.), tensor(0.7820))

In [15]:
pred_log = torch.log(pred)

In [25]:
F.cross_entropy(logits, torch.tensor([3])) # 已经包括了softmax和log的步骤

tensor(52.0586)

In [18]:
F.nll_loss(pred_log, torch.tensor([3])) # 不实用cross_entropy， 自己算的方式

tensor(52.0586)

## 多分类问题实战

In [29]:
w1, b1 = torch.randn(200, 784, requires_grad=True), torch.zeros(200, requires_grad=True)
w2, b2 = torch.randn(200, 200, requires_grad=True), torch.zeros(200, requires_grad=True)
w3, b3 = torch.randn(10, 200, requires_grad=True), torch.zeros(10, requires_grad=True)

In [30]:
def forward(x):
  x = x@w1.t() + b1
  x = F.relu(x)
  x = x@w2.t() + b2
  x = F.relu(x)
  x = x@w3.t() + b3
  x = F.relu(x)
  return x

In [39]:
learning_rate = 0.01
epochs = 10
optimizer = torch.optim.SGD([w1, b1, w2, b2, w3, b3], lr=learning_rate)

In [40]:
criteon = torch.nn.CrossEntropyLoss()

In [41]:
for epoch in range(epochs):
  for batch_idx, (data, target) in enumerate(train_loader):
    data = data.view(-1, 28*28)
    logits = forward(data)
    loss = criteon(logits, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

NameError: ignored